### PR TITLE
Replace Kotlin with Java implementation for easier project maintenance.

### PR DESCRIPTION
**Pull request by ened**
Unless you have a **strong** need for Kotlin, simple plugins should be written in Java to keep compile times fast and external dependencies plus maintenance tasks small.

### CODE REVIEW

**Comment by Vanethos** [comment]
Sorry for taking so long to reply.

You are absolutely right, it is in fact way easier to maintain and it has the added advantage that more people can read and learn from it.

thank you for your pull request!

**Comment by ened** [comment]
@Vanethos Thx for merging. Will you release it on pub soon?

**Comment by Vanethos** [comment]
Yes! I will try to release it between today and tomorrow

**Comment by Vanethos** [comment]
In the meantime, after merging I found one small bug: it is `ACTION_APPLICATION_DETAILS_SETTINGS` and not `ACTION_APPLICATION_SETTINGS`

**Pull request merged**
